import Layout from "@/components/Layout";
import Head from "next/head";
import profilePic from "../../public/images/profile/svb1.png";
import Image from "next/image";
import { motion } from "framer-motion";
import AnimatedText from "@/components/AnimatedText";
export default function Home() {
  return (
    <>
      <Head>
        <title>Rakshith Shetty</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex justify-between w-full items-center gap-4">
            <motion.div className="w-1/2"
              whileHover={{ scale: 1.2 }}
            >
              <Image
                src={profilePic}
                className="w-full h-auto rounded-full transform -scale-x-100"
                alt="img"
              />
            </motion.div>
            <div>
             
              <AnimatedText text={"Rakshith Shetty"} />
              <p className="flex text-center justify-center items-center font-medium">Jr. Full Stack Developer</p>
           <div className="flex text-center items-center my-4 justify-evenly">
            {/* <a href="" className="bg-dark text-lime-50 p-2 text-2xl rounded-md">Resume </a>
            <a href="mailto@" className="p-2 text-2xl rounded-md">Contact</a> */}
           </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
